### ISSUE TITLE
Application could not be installed

### ISSUE THREAD

**Issue by YuleZ** [YunoHost-Apps/openvpn_ynh#38]
I pasted the github-repository-url into yunohost's "Custom App" textfield and clicked install and it could not be installed.

My yunohost is freshly installed.

Versions:
yunohost -> 3.4.2.4 (stable)
yunohost-admin -> 3.4.2 (stable)
moulinette -> 3.4.2 (stable)
ssowat -> 3.4.2 (stable)

Here my Log-Output:

2019-03-01 12:33:30,782: DEBUG - Führe den Behfehl 'sh -c YNH_APP_ARG_IP4RANGES=123.123.123.123 YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/openvpn_ynh-master/scripts YNH_STDINFO=/tmp/tmpu9NUiB/stdinfo YNH_APP_ARG_DEDICATED_IP=123.123.123.123 YNH_APP_INSTANCE_NAME=openvpn YNH_APP_ID=openvpn YNH_APP_ARG_PATH=/openvpn YNH_APP_ARG_DOMAIN=domain.tld BASH_XTRACEFD=7 /bin/bash -x "./install" domain.tld /openvpn 123.123.123.123 123.123.123.123 openvpn 7>&1' aus...
2019-03-01 12:33:30,783: DEBUG - About to run the command '['sh', '-c', 'YNH_APP_ARG_IP4RANGES=123.123.123.123 YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/openvpn_ynh-master/scripts YNH_STDINFO=/tmp/tmpu9NUiB/stdinfo YNH_APP_ARG_DEDICATED_IP=123.123.123.123 YNH_APP_INSTANCE_NAME=openvpn YNH_APP_ID=openvpn YNH_APP_ARG_PATH=/openvpn YNH_APP_ARG_DOMAIN=domain.tld BASH_XTRACEFD=7 /bin/bash -x "./install" domain.tld /openvpn 123.123.123.123 123.123.123.123 openvpn 7>&1']'
2019-03-01 12:33:30,791: DEBUG - + source /usr/share/yunohost/helpers
2019-03-01 12:33:30,791: DEBUG - +++ run-parts --list /usr/share/yunohost/helpers.d
2019-03-01 12:33:30,792: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,792: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
2019-03-01 12:33:30,792: DEBUG - ++ . /usr/share/yunohost/helpers.d/backend
2019-03-01 12:33:30,792: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,792: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
2019-03-01 12:33:30,792: DEBUG - ++ . /usr/share/yunohost/helpers.d/filesystem
2019-03-01 12:33:30,793: DEBUG - +++ CAN_BIND=1
2019-03-01 12:33:30,793: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,793: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/getopts ']'
2019-03-01 12:33:30,793: DEBUG - ++ . /usr/share/yunohost/helpers.d/getopts
2019-03-01 12:33:30,793: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,793: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
2019-03-01 12:33:30,793: DEBUG - ++ . /usr/share/yunohost/helpers.d/ip
2019-03-01 12:33:30,793: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,794: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
2019-03-01 12:33:30,794: DEBUG - ++ . /usr/share/yunohost/helpers.d/mysql
2019-03-01 12:33:30,794: DEBUG - +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
2019-03-01 12:33:30,794: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,794: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/network ']'
2019-03-01 12:33:30,794: DEBUG - ++ . /usr/share/yunohost/helpers.d/network
2019-03-01 12:33:30,794: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,795: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/nodejs ']'
2019-03-01 12:33:30,795: DEBUG - ++ . /usr/share/yunohost/helpers.d/nodejs
2019-03-01 12:33:30,795: DEBUG - +++ n_install_dir=/opt/node_n
2019-03-01 12:33:30,795: DEBUG - +++ node_version_path=/opt/node_n/n/versions/node
2019-03-01 12:33:30,795: DEBUG - +++ export N_PREFIX=/opt/node_n
2019-03-01 12:33:30,795: DEBUG - +++ N_PREFIX=/opt/node_n
2019-03-01 12:33:30,795: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,796: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/package ']'
2019-03-01 12:33:30,796: DEBUG - ++ . /usr/share/yunohost/helpers.d/package
2019-03-01 12:33:30,896: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,896: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/print ']'
2019-03-01 12:33:30,896: DEBUG - ++ . /usr/share/yunohost/helpers.d/print
2019-03-01 12:33:30,896: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,897: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/psql ']'
2019-03-01 12:33:30,897: DEBUG - ++ . /usr/share/yunohost/helpers.d/psql
2019-03-01 12:33:30,897: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,897: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
2019-03-01 12:33:30,897: DEBUG - ++ . /usr/share/yunohost/helpers.d/setting
2019-03-01 12:33:30,897: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,897: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
2019-03-01 12:33:30,897: DEBUG - ++ . /usr/share/yunohost/helpers.d/string
2019-03-01 12:33:30,897: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,898: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/system ']'
2019-03-01 12:33:30,898: DEBUG - ++ . /usr/share/yunohost/helpers.d/system
2019-03-01 12:33:30,898: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,898: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
2019-03-01 12:33:30,898: DEBUG - ++ . /usr/share/yunohost/helpers.d/user
2019-03-01 12:33:30,898: DEBUG - ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
2019-03-01 12:33:30,898: DEBUG - ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
2019-03-01 12:33:30,898: DEBUG - ++ . /usr/share/yunohost/helpers.d/utils
2019-03-01 12:33:30,898: DEBUG - + source _common.sh
2019-03-01 12:33:30,899: DEBUG - +++ cd ../
2019-03-01 12:33:30,899: DEBUG - +++ pwd
2019-03-01 12:33:30,899: DEBUG - ++ PKG_DIR=/var/cache/yunohost/from_file/openvpn_ynh-master
2019-03-01 12:33:30,899: DEBUG - + ynh_trap_on
2019-03-01 12:33:30,899: DEBUG - + set -eu
2019-03-01 12:33:30,899: DEBUG - + trap ynh_exit_properly EXIT
2019-03-01 12:33:30,899: DEBUG - + export app=openvpn
2019-03-01 12:33:30,899: DEBUG - + app=openvpn
2019-03-01 12:33:30,899: DEBUG - + export user=openvpn
2019-03-01 12:33:30,899: DEBUG - + user=openvpn
2019-03-01 12:33:30,900: DEBUG - + export webuser=openvpnweb
2019-03-01 12:33:30,900: DEBUG - + webuser=openvpnweb
2019-03-01 12:33:30,900: DEBUG - + ynh_export domain path ip4ranges dedicated_ip
2019-03-01 12:33:30,900: DEBUG - + local ynh_arg=
2019-03-01 12:33:30,900: DEBUG - + for var in $@
2019-03-01 12:33:30,900: DEBUG - ++ echo domain
2019-03-01 12:33:30,900: DEBUG - ++ awk '{print toupper($0)}'
2019-03-01 12:33:30,900: DEBUG - + ynh_arg=DOMAIN
2019-03-01 12:33:30,900: DEBUG - + ynh_arg=YNH_APP_ARG_DOMAIN
2019-03-01 12:33:30,900: DEBUG - + export domain=domain.tld
2019-03-01 12:33:30,900: DEBUG - + domain=domain.tld
2019-03-01 12:33:30,901: DEBUG - + for var in $@
2019-03-01 12:33:30,901: DEBUG - ++ echo path
2019-03-01 12:33:30,901: DEBUG - ++ awk '{print toupper($0)}'
2019-03-01 12:33:30,901: DEBUG - + ynh_arg=PATH
2019-03-01 12:33:30,901: DEBUG - + ynh_arg=YNH_APP_ARG_PATH
2019-03-01 12:33:30,901: DEBUG - + export path=/openvpn
2019-03-01 12:33:30,901: DEBUG - + path=/openvpn
2019-03-01 12:33:30,901: DEBUG - + for var in $@
2019-03-01 12:33:30,901: DEBUG - ++ echo ip4ranges
2019-03-01 12:33:30,901: DEBUG - ++ awk '{print toupper($0)}'
2019-03-01 12:33:30,902: DEBUG - + ynh_arg=IP4RANGES
2019-03-01 12:33:30,902: DEBUG - + ynh_arg=YNH_APP_ARG_IP4RANGES
2019-03-01 12:33:30,902: DEBUG - + export ip4ranges=123.123.123.123
2019-03-01 12:33:30,902: DEBUG - + ip4ranges=123.123.123.123
2019-03-01 12:33:30,902: DEBUG - + for var in $@
2019-03-01 12:33:30,902: DEBUG - ++ echo dedicated_ip
2019-03-01 12:33:30,902: DEBUG - ++ awk '{print toupper($0)}'
2019-03-01 12:33:30,902: DEBUG - + ynh_arg=DEDICATED_IP
2019-03-01 12:33:30,902: DEBUG - + ynh_arg=YNH_APP_ARG_DEDICATED_IP
2019-03-01 12:33:30,902: DEBUG - + export dedicated_ip=123.123.123.123
2019-03-01 12:33:30,903: DEBUG - + dedicated_ip=123.123.123.123
2019-03-01 12:33:30,903: DEBUG - + ynh_find_port 1194
2019-03-01 12:33:30,903: DEBUG - + port=1194
2019-03-01 12:33:30,903: DEBUG - + test -n 1194
2019-03-01 12:33:30,903: DEBUG - + netcat -z 127.0.0.1 1194
2019-03-01 12:33:30,903: DEBUG - + echo 1194
2019-03-01 12:33:30,903: DEBUG - 1194
2019-03-01 12:33:30,903: DEBUG - + export port=1194
2019-03-01 12:33:30,903: DEBUG - + port=1194
2019-03-01 12:33:30,903: DEBUG - + export local_path=/var/www/openvpn
2019-03-01 12:33:30,904: DEBUG - + local_path=/var/www/openvpn
2019-03-01 12:33:30,904: DEBUG - ++ ip r
2019-03-01 12:33:30,904: DEBUG - ++ awk '/default/ { print $5 }'
2019-03-01 12:33:30,904: DEBUG - + export iface=enp4s0
2019-03-01 12:33:30,904: DEBUG - + iface=enp4s0
2019-03-01 12:33:30,904: DEBUG - + ynh_check_var openvpn 'app name not set'
2019-03-01 12:33:30,904: DEBUG - + test -n openvpn
2019-03-01 12:33:30,904: DEBUG - + ynh_normalize_url_path /openvpn
2019-03-01 12:33:30,904: DEBUG - + path=/openvpn
2019-03-01 12:33:30,904: DEBUG - + test -n /openvpn
2019-03-01 12:33:30,905: DEBUG - + '[' / '!=' / ']'
2019-03-01 12:33:30,905: DEBUG - + '[' n == / ']'
2019-03-01 12:33:30,905: DEBUG - + echo /openvpn
2019-03-01 12:33:30,905: DEBUG - /openvpn
2019-03-01 12:33:30,905: DEBUG - + ynh_path_validity domain.tld/openvpn
2019-03-01 12:33:30,905: DEBUG - + sudo yunohost app checkurl domain.tld/openvpn -a openvpn
2019-03-01 12:33:31,005: WARNING - 'yunohost app checkurl' is deprecated and will be removed in the future
2019-03-01 12:33:31,006: WARNING - Packagers /!\ : 'app checkurl' is deprecated ! Please use the helper 'ynh_webpath_register' instead !
2019-03-01 12:33:31,107: DEBUG - + ynh_local_path_available /var/www/openvpn
2019-03-01 12:33:31,107: DEBUG - + '[' -e /var/www/openvpn ']'
2019-03-01 12:33:31,107: DEBUG - + check_iptables
2019-03-01 12:33:31,107: DEBUG - + sudo iptables -L
2019-03-01 12:33:31,107: DEBUG - + check_tun_available
2019-03-01 12:33:31,107: DEBUG - + return 0
2019-03-01 12:33:31,108: DEBUG - + check_ip4ranges 123.123.123.123
2019-03-01 12:33:31,108: DEBUG - + _255='(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)'
2019-03-01 12:33:31,108: DEBUG - + ip4regex='((25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)'
2019-03-01 12:33:31,108: DEBUG - + rangeip4regex='((25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)(/(3[0-2]|[1-2][0-9]|[1-9]))?'
2019-03-01 12:33:31,108: DEBUG - + regex='((25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)(/(3[0-2]|[1-2][0-9]|[1-9]))?([[:space:]]+((25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)(/(3[0-2]|[1-2][0-9]|[1-9]))?)*'
2019-03-01 12:33:31,108: DEBUG - + [[ 123.123.123.123 =~ ^((25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)(/(3[0-2]|[1-2][0-9]|[1-9]))?([[:space:]]+((25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)(/(3[0-2]|[1-2][0-9]|[1-9]))?)*$ ]]
2019-03-01 12:33:31,109: DEBUG - + return 0
2019-03-01 12:33:31,109: DEBUG - + ynh_save_args ip4ranges port local_path iface dedicated_ip
2019-03-01 12:33:31,109: DEBUG - + for var in $@
2019-03-01 12:33:31,109: DEBUG - + ynh_app_setting_set openvpn ip4ranges 123.123.123.123
2019-03-01 12:33:31,109: DEBUG - + sudo yunohost app setting openvpn ip4ranges --value=123.123.123.123 --quiet
2019-03-01 12:33:31,310: DEBUG - + for var in $@
2019-03-01 12:33:31,310: DEBUG - + ynh_app_setting_set openvpn port 1194
2019-03-01 12:33:31,310: DEBUG - + sudo yunohost app setting openvpn port --value=1194 --quiet
2019-03-01 12:33:31,510: DEBUG - + for var in $@
2019-03-01 12:33:31,511: DEBUG - + ynh_app_setting_set openvpn local_path /var/www/openvpn
2019-03-01 12:33:31,511: DEBUG - + sudo yunohost app setting openvpn local_path --value=/var/www/openvpn --quiet
2019-03-01 12:33:31,712: DEBUG - + for var in $@
2019-03-01 12:33:31,712: DEBUG - + ynh_app_setting_set openvpn iface enp4s0
2019-03-01 12:33:31,712: DEBUG - + sudo yunohost app setting openvpn iface --value=enp4s0 --quiet
2019-03-01 12:33:31,913: DEBUG - + for var in $@
2019-03-01 12:33:31,913: DEBUG - + ynh_app_setting_set openvpn dedicated_ip 123.123.123.123
2019-03-01 12:33:31,913: DEBUG - + sudo yunohost app setting openvpn dedicated_ip --value=123.123.123.123 --quiet
2019-03-01 12:33:32,114: DEBUG - + ynh_app_dependencies openvpn,openvpn-auth-ldap,netmask
2019-03-01 12:33:32,114: WARNING - Traceback (most recent call last):
2019-03-01 12:33:32,114: DEBUG - + export dependencies=openvpn,openvpn-auth-ldap,netmask
2019-03-01 12:33:32,114: WARNING -   File "<string>", line 1, in <module>
2019-03-01 12:33:32,115: DEBUG - + dependencies=openvpn,openvpn-auth-ldap,netmask
2019-03-01 12:33:32,115: WARNING -   File "/usr/lib/python3.5/json/__init__.py", line 265, in load
2019-03-01 12:33:32,115: DEBUG - ++ ynh_read_manifest url
2019-03-01 12:33:32,115: WARNING -     return loads(fp.read(),
2019-03-01 12:33:32,115: DEBUG - ++ '[' -f ../manifest.json ']'
2019-03-01 12:33:32,115: WARNING -   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
2019-03-01 12:33:32,115: DEBUG - ++ ynh_read_json ../manifest.json url
2019-03-01 12:33:32,116: WARNING -     return codecs.ascii_decode(input, self.errors)[0]
2019-03-01 12:33:32,116: DEBUG - ++ sudo python3 -c 'import sys, json;print(json.load(open('\''../manifest.json'\''))['\''url'\''])'
2019-03-01 12:33:32,116: WARNING - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 198: ordinal not in range(128)
2019-03-01 12:33:32,116: DEBUG - + export project_url=
2019-03-01 12:33:32,116: DEBUG - + project_url=
2019-03-01 12:33:32,116: DEBUG - ++ ynh_read_manifest version
2019-03-01 12:33:32,116: DEBUG - ++ '[' -f ../manifest.json ']'
2019-03-01 12:33:32,116: DEBUG - ++ ynh_read_json ../manifest.json version
2019-03-01 12:33:32,116: DEBUG - ++ sudo python3 -c 'import sys, json;print(json.load(open('\''../manifest.json'\''))['\''version'\''])'
2019-03-01 12:33:32,217: DEBUG - + export version=
2019-03-01 12:33:32,217: WARNING - Traceback (most recent call last):
2019-03-01 12:33:32,217: DEBUG - + version=
2019-03-01 12:33:32,218: WARNING -   File "<string>", line 1, in <module>
2019-03-01 12:33:32,218: DEBUG - + export dep_app=openvpn
2019-03-01 12:33:32,218: WARNING -   File "/usr/lib/python3.5/json/__init__.py", line 265, in load
2019-03-01 12:33:32,218: DEBUG - + dep_app=openvpn
2019-03-01 12:33:32,219: WARNING -     return loads(fp.read(),
2019-03-01 12:33:32,219: DEBUG - + mkdir -p ../conf
2019-03-01 12:33:32,219: WARNING -   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
2019-03-01 12:33:32,219: DEBUG - + cat
2019-03-01 12:33:32,220: WARNING -     return codecs.ascii_decode(input, self.errors)[0]
2019-03-01 12:33:32,220: DEBUG - + ynh_configure app-ynh-deps.control ./openvpn-ynh-deps.control
2019-03-01 12:33:32,220: WARNING - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 198: ordinal not in range(128)
2019-03-01 12:33:32,220: DEBUG - + local TEMPLATE=app-ynh-deps.control
2019-03-01 12:33:32,220: DEBUG - + local DEST=./openvpn-ynh-deps.control
2019-03-01 12:33:32,221: DEBUG - + type j2
2019-03-01 12:33:32,221: DEBUG - j2 is /usr/local/bin/j2
2019-03-01 12:33:32,221: DEBUG - + j2 /var/cache/yunohost/from_file/openvpn_ynh-master/conf/app-ynh-deps.control.j2
2019-03-01 12:33:32,522: DEBUG - + sudo cp /var/cache/yunohost/from_file/openvpn_ynh-master/conf/app-ynh-deps.control ./openvpn-ynh-deps.control
2019-03-01 12:33:32,522: WARNING - 
2019-03-01 12:33:32,523: DEBUG - + ynh_package_install_from_equivs ./openvpn-ynh-deps.control
2019-03-01 12:33:32,523: DEBUG - + local controlfile=./openvpn-ynh-deps.control
2019-03-01 12:33:32,523: DEBUG - ++ grep '^Package: ' ./openvpn-ynh-deps.control
2019-03-01 12:33:32,523: DEBUG - ++ cut '-d ' -f 2
2019-03-01 12:33:32,523: DEBUG - + local pkgname=openvpn-ynh-deps
2019-03-01 12:33:32,524: DEBUG - ++ grep '^Version: ' ./openvpn-ynh-deps.control
2019-03-01 12:33:32,524: DEBUG - ++ cut '-d ' -f 2
2019-03-01 12:33:32,524: DEBUG - + local pkgversion=
2019-03-01 12:33:32,524: DEBUG - + [[ -z openvpn-ynh-deps ]]
2019-03-01 12:33:32,524: DEBUG - + [[ -z '' ]]
2019-03-01 12:33:32,525: DEBUG - + echo 'Invalid control file'
2019-03-01 12:33:32,525: DEBUG - Invalid control file
2019-03-01 12:33:32,525: DEBUG - + exit 1
2019-03-01 12:33:32,525: DEBUG - + ynh_exit_properly
2019-03-01 12:33:32,526: DEBUG - + exit_code=1
2019-03-01 12:33:32,526: DEBUG - + '[' 1 -eq 0 ']'
2019-03-01 12:33:32,526: DEBUG - + trap '' EXIT
2019-03-01 12:33:32,526: DEBUG - + set +eu
2019-03-01 12:33:32,526: DEBUG - + echo -e '\e[91m \e[1m'
2019-03-01 12:33:32,527: DEBUG - [91m [1m
2019-03-01 12:33:32,527: DEBUG - + err 'openvpn script has encountered an error.'
2019-03-01 12:33:32,527: DEBUG - + log '[ERR] openvpn script has encountered an error.'
2019-03-01 12:33:32,527: DEBUG - + echo '[ERR] openvpn script has encountered an error.'
2019-03-01 12:33:32,527: DEBUG - [ERR] openvpn script has encountered an error.
2019-03-01 12:33:32,528: DEBUG - + type -t CLEAN_SETUP
2019-03-01 12:33:32,528: DEBUG - + ynh_die
2019-03-01 12:33:32,528: DEBUG - + echo ''
2019-03-01 12:33:32,528: DEBUG - + exit 1

is there another vpn-server plugin I can use?

**Comment by stemy2** [comment]
Same problem, [my install log](https://paste.yunohost.org/raw/yahecorove).

**Comment by YuleZ** [comment]
I made #44 to fix this issue. Feel free to try it out.

**Comment by stemy2** [comment]
I tested again, [it failed again](https://paste.yunohost.org/raw/loloyehoja).

**Comment by YuleZ** [comment]
The PR isn‘t merged yet. If you want, try my fork.
